url: https://tapasmishra.github.io
baseurl: /

# Site settings
title: LinuxFunda
email: tapas.mishra@linuxfunda.com
description: "Tapas Mishra Profile page"


# Team names, titles and social links
people:
 - name: Tapas Mishra
   pic: 1
   position: Lead Designer
   social:
     - title: twitter
       url: #
     - title: facebook
       url: #
     - title: stack-overflow
       url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/linuxfunda
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/linuxfunda
  - title: github
    url: http://github.com/tapasmishra

# Postal address (add as many lines as necessary)
address:
  - line: U-804, Sai Pearl, Near Alcove
  - line: Kunal Icon Road, Pimple Sudagar, Pune, India - 4011027

# Build settings
markdown: kramdown
permalink: pretty
