title: Welcome to LinuxFunda
description: This is a blog site for DevOps lovers. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "tapasmishra.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author
author-name:    Tapas Mishra
author-image:   1.jpg
author-job:     Lead Software Engineer
author-email:   tapas.mishra@linuxfunda.com # Add your email for contant form.
author-facebook: linuxfunda # Add your twitter account
about-author:   I am a software developer focusing on DevOps principles. Always hungry to keep learning.

# Social settings
social-twitter:   linuxfunda
social-facebook:
social-github:    tapasmishra
social-pinterest: 
social-instagram: tspaspreeti
social-youtube:
social-vk:   
social-linkedin:

# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1

# Comment Section (Disqus)
disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-paginate

paginate: 7
paginate_path: "/page/:num/"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
